[package]
name = "syntask"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-actors = "4"
actix = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
